// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    Updating: typeof import('./theme/components/Updating.vue')['default']
  }
}
